### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by hashworks**
Mainly to add notes about tinyxml2 versions, resolves #79.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@hashworks a patched version of 4.0.1 [has been released](https://github.com/ros/rospack/issues/77#issuecomment-322328343) for the affected platforms targeted by ROS Lunar (Ubuntu Yakkety, Ubuntu Zesty and Debian Stretch). For anybody having the ros apt repository in its sources, apt will install the patched version (4.0.1-2) that will also work with `rospack`.

**Comment by hashworks** [comment]
Note that the ros apt repositories don't include binaries for all
architectures.

Am 24.08.2017 00:13 schrieb "Mikael Arguedas" <notifications@github.com>:

@hashworks <https://github.com/hashworks> a patched version of 4.0.1 has
been released
<https://github.com/ros/rospack/issues/77#issuecomment-322328343> for the
affected platforms targeted by ROS Lunar (Ubuntu Yakkety, Ubuntu Zesty and
Debian Stretch). For anybody having the ros apt repository in its sources,
apt will install the patched version (4.0.1-2) that will also work with
rospack.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashworks/rospack/pull/1#issuecomment-324477734>, or mute
the thread

**Comment by hashworks** [comment]
(However, I'm gonna add that in a commit tomorrow)

Am 24.08.2017 01:21 schrieb "hashworks" <mail@hashworks.net>:

Note that the ros apt repositories don't include binaries for all
architectures.


Am 24.08.2017 00:13 schrieb "Mikael Arguedas" <notifications@github.com>:

@hashworks <https://github.com/hashworks> a patched version of 4.0.1 has
been released
<https://github.com/ros/rospack/issues/77#issuecomment-322328343> for the
affected platforms targeted by ROS Lunar (Ubuntu Yakkety, Ubuntu Zesty and
Debian Stretch). For anybody having the ros apt repository in its sources,
apt will install the patched version (4.0.1-2) that will also work with
rospack.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashworks/rospack/pull/1#issuecomment-324477734>, or mute
the thread

**Comment by mikaelarguedas** [comment]
> Note that the ros apt repositories don't include binaries for all
architectures.

That's correct. Indeed I should have specified it has been backported only by the affected platform/architecture pairs targeted by ROS Lunar (the ones we build debian packages for). So if a user is building ROS from source, he/she will likely need to build a patched version of the package themselves.

**Comment by kamalpandey1993** [comment]
@mikaelarguedas could you help me provide a patch for debian stretch or tell me how to make this work for that OS . I have this issue  [ https://answers.ros.org/question/278733/rospack-find-throws-exception-error/](url)

**Comment by mikaelarguedas** [comment]
@kamalpandey1993  see https://github.com/ros/rospack/issues/77#issuecomment-356619084
As mentionned by other maintainers, posting your issue in multiple (and unrelated) places is considered bad etiquette http://wiki.ros.org/Support#Etiquette please post your question in a single place in the future.

**Pull request closed without merging**
